---
- name: Install PHP 7.1
  apt: name=php7.1 state=present

- name: Install PHP Modules
  apt: name={{ item }} state=present
  with_items:
    - php-mysql
    - libapache2-mod-php
    - php-curl
    - php-imagick
    - php-json
    - php-mbstring
    - php-ssh2
    - php-xdebug
    - php-xml
    - php-mcrypt
    - composer