---
- name: Install PHP 7
  apt: name=php7.0 state=present

- name: Install PHP Modules
  apt: name={{ item }} state=present
  with_items:
    - php7.0-mysql
    - libapache2-mod-php7.0
    - php7.0-curl