---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  remote_user: root
  gather_facts: false
  pre_tasks:
    - raw: sudo apt-get update && apt-get -y install python-minimal python-pip
    - action: setup
  vars:
    document_root: /vagrant
  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded
    - name: restart apache
      service: name=apache2 state=restarted
  tasks:
  - name: Update apt cache
    apt: update_cache=yes
  - include: tasks/apache.yml
  - include: tasks/php.yml
  - include: tasks/php.custom.yml
  roles:
    - role: geerlingguy.mysql
      become: yes
